# Utilizar una imagen de OpenJDK con Alpine Linux
FROM openjdk:17-jdk-alpine

# Copiar el archivo JAR generado al contenedor
COPY target/api-0.0.1-SNAPSHOT.jar java-app.jar

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "java-app.jar"]
